#!/bin/bash

# Django Settings
export SECRET_KEY=YOUR DJANGO SECRET KEY
export ALLOWED_HOSTS=HOSTS SEPARATED BY COMMAS
export DEBUG=True

# QBO Settings
export QBO_CLIENT_ID=QBO_CLIENT_ID
export QBO_CLIENT_SECRET=QBO_CLIENT_SECRET
export REDIRECT_URI=REDIRECT_URI
export QBO_SCOPE=QBO_SCOPE
export QBO_TOKEN_URL=QBO_TOKEN_URL
export QBO_AUTH_ENDPOINT=QBO_AUTH_ENDPOINT

# XERO Settings
export XERO_CLIENT_ID=XERO_CLIENT_ID
export XERO_CLIENT_SECRET=XERO_CLIENT_SECRET
export XERO_REDIRECT_URI=XERO_REDIRECT_URI
export XERO_SCOPE=XERO_SCOPE
export XERO_TOKEN_URL=XERO_TOKEN_URL
export XERO_AUTH_ENDPOINT=XERO_AUTH_ENDPOINT

# Email Settings
export EMAIL_USE_TLS=True
export EMAIL_HOST=EMAIL_HOST
export EMAIL_PORT=EMAIL_PORT
export EMAIL_HOST_USER=EMAIL_HOST_USER
export EMAIL_HOST_PASSWORD=EMAIL_HOST_PASSWORD
export TO_EMAIL=TO_EMAIL
